package co.edu.javeriana.mc.survey.repository.multi;

import co.edu.javeriana.mc.survey.model.multi.SingleSelectionMultipleChoice;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 14/09/2021
*/
@Repository
public interface SingleSelectionMultipleChoiceRepository extends JpaRepository<SingleSelectionMultipleChoice, Long>, JpaSpecificationExecutor<SingleSelectionMultipleChoice> {

}
