package co.edu.javeriana.mc.survey.repository.scalars;

import co.edu.javeriana.mc.survey.model.scalars.MultiLineQuestion;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 14/09/2021
*/
@Repository
public interface MultiLineQuestionRepository extends JpaRepository<MultiLineQuestion, Long>, JpaSpecificationExecutor<MultiLineQuestion> {

}
