package co.edu.javeriana.mc.survey.repository.multi.choices;

import co.edu.javeriana.mc.survey.model.multi.choices.IntegerChoice;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 14/09/2021
*/
@Repository
public interface IntegerChoiceRepository extends JpaRepository<IntegerChoice, Long>, JpaSpecificationExecutor<IntegerChoice> {

}
