package co.edu.javeriana.mc.survey.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import co.edu.javeriana.mc.survey.model.SurveyItem;

/**
* Generated by Spring Data Generator on 14/09/2021
*/
@Repository
public interface SurveyItemRepository extends JpaRepository<SurveyItem, Long>, JpaSpecificationExecutor<SurveyItem> {

}
